### ISSUE TITLE
Add section about Fyde app

### ISSUE THREAD

**Issue by luisalima** [fyde/docs#52]
1. What the app does (security + resource access)
  a. How does the network monitoring work, per platform
2. Installation
  a. On the linux case, we should explain how we use systemd, and how to install it manually on non-debian
3. Enrollment process
  a. Talk about how it works, the certificate issuance, its security
4. Security-related
  a. How it works, how we curate the lists
5. Resource-related
  a. Authorization process
  b. Remediations
6. Known issues
  e.g. Windows - sometimes VPN does not install
7. Troubleshooting
  a. Some technical help for admins to debug more complex problems (and how they report it back to us)

**Comment by rasmartins** [comment]
Instead of "sometimes VPN does not install" it should be "after an upgrade the VPN might fail to connect"

**Comment by luisalima** [comment]
👍 thanks @rasmartins !
