### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by luisalima** [fyde/docs#60]
We should add a section with API documentation, as well as cURL commands for common operations while we do not have the fyde cli in place.

cc @oNaiPs and @rpereira

**Comment by rpereira** [comment]
@luisalima, I just pushed some initial content to https://github.com/fyde/docs/tree/60-api-docs

**Comment by oNaiPs** [comment]
Guys it would be nice to use our swagger spec to generate this page (or a part of it) as well.

Something like this https://idratherbewriting.com/learnapidoc/pubapis_combine_swagger_and_guide.html

**Comment by luisalima** [comment]
@oNaiPs I totally agree, that's the point of swagger, but I think that @rpereira 's "manual" proposal is just meant to talk about the general ideas of the API right?
